# Generated by Django 6.1.1 on 2026-09-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_conversation_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_reports', to='marketplace.profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.product'),
        ),
    ]
