# Generated by Django 6.1.1 on 2026-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_profile_store_name_profile_theme_background_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme_background_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_background',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/backgrounds/'),
        ),
    ]
