# Generated by Django 4.2.30 on 2026-10-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_productreport_storereport_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='product',
        ),
        migrations.AddField(
            model_name='profile',
            name='layout_style',
            field=models.CharField(choices=[('TABS', 'Classic Tabs'), ('SIDEBAR', 'Sidebar Split (Q&A + Reviews Right)'), ('FEED', 'Featured & Review Ticker'), ('BAZAAR', 'Bazaar Showcase (Store Info Left)')], default='TABS', max_length=20),
        ),
    ]
